// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLpS4M-oVzBlbyo90OZp_3QR3_fJbDMQ',
    appId: '1:1035202227051:web:f30aa47b7959f753e97a2e',
    messagingSenderId: '1035202227051',
    projectId: 'carpool-400820',
    authDomain: 'carpool-400820.firebaseapp.com',
    storageBucket: 'carpool-400820.appspot.com',
    measurementId: 'G-DZ0V25H7PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLj0i8LmXXbjZWVyKr2FLusNE-6fORRTA',
    appId: '1:1035202227051:android:63a5307092ed1cc4e97a2e',
    messagingSenderId: '1035202227051',
    projectId: 'carpool-400820',
    storageBucket: 'carpool-400820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8re3jmn7lM_dDb8Qllj1E45pbIQ20IoU',
    appId: '1:1035202227051:ios:66f718a9fb110520e97a2e',
    messagingSenderId: '1035202227051',
    projectId: 'carpool-400820',
    storageBucket: 'carpool-400820.appspot.com',
    iosBundleId: 'com.example.carpooling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8re3jmn7lM_dDb8Qllj1E45pbIQ20IoU',
    appId: '1:1035202227051:ios:638a780964d523b2e97a2e',
    messagingSenderId: '1035202227051',
    projectId: 'carpool-400820',
    storageBucket: 'carpool-400820.appspot.com',
    iosBundleId: 'com.example.carpooling.RunnerTests',
  );
}
